[build]
  command = "npm run build"
  publish = "build/client"

[dev]
  command = "npm run dev"
  targetPort = 3000
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200