[build]
  command = "react-router build"
  publish = "build/client"

[dev]
  command = "react-router dev"

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200