[build.environment]
  NODE_ENV = "development"

[build]
  command = "npm run build"
  publish = "build/client"

[dev]
  command = "npm run dev"
  targetPort = 3000
  framework = "vite"

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200